Divisima/Divisima/Divisima.UI/Areas/admin/Controllers/ProductController.cs
using System.Reflection.Metadata;
using Divisima.BL.Repositories;
using Divisima.DAL.Entities;
using Divisima.UI.Areas.admin.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Divisima.UI.Areas.admin.Controllers
{
	[Area("admin"), Authorize]
	public class ProductController : Controller
	{
		IRepository<Product> repoProduct;

		IRepository<Brand> repoBrand;
		IRepository<Category> repoCategory;

		public ProductController(IRepository<Product> _repoProduct, IRepository<Brand> _repoBrand, IRepository<Category> _repoCategory)
        {
			repoProduct = _repoProduct;
			repoBrand = _repoBrand;
			repoCategory = _repoCategory;
        }
        public IActionResult Index()
		{
			return View(repoProduct.GetAll().OrderByDescending(x => x.ID));
		}

		public IActionResult New()
		{
			ProductVM productVM = new ProductVM
			{
				Product = new Product(),
				Brands = repoBrand.GetAll().OrderBy(x => x.Name),
				Categories = repoCategory.GetAll(x => x.ParentID!=null).OrderBy(x => x.Name)
			};
			return View(productVM);
		}

		[HttpPost, ValidateAntiForgeryToken]
		public  IActionResult Insert(ProductVM model)
		{
			if (ModelState.IsValid)
			{
				repoProduct.Add(model.Product);

				return RedirectToAction("Index");
			}
			else return RedirectToAction("New");
		}


		public ActionResult Edit(int productid)
		{
			Product product = repoProduct.GetBy(x => x.ID == productid);
			ProductVM productVM = new ProductVM
			{
				Product = product,
				Brands = repoBrand.GetAll().OrderBy(x => x.Name),
				Categories = repoCategory.GetAll(x => x.ParentID != null).OrderBy(x => x.Name)
			};
			if (product != null) return View(productVM);
			else return RedirectToAction("Index");
		}

		[HttpPost, ValidateAntiForgeryToken]
		public IActionResult Edit(ProductVM model)
		{
			if (ModelState.IsValid) 
			{
				repoProduct.Update(model.Product);

				return RedirectToAction("Index");
			}
			else return RedirectToAction("New");
		}


		public IActionResult Delete(int id)
		{
			Product Product = repoProduct.GetBy(x => x.ID == id);
			if (Product != null) repoProduct.Delete(Product);
			return RedirectToAction("Index");
		}
	}
}

Divisima/Divisima/Divisima.UI/Controllers/ProductController.cs
using Divisima.BL.Repositories;
using Divisima.DAL.Entities;
using Divisima.UI.Models;
using Divisima.UI.Tools;
using Divisima.UI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ApplicationParts;
using Microsoft.EntityFrameworkCore;
using NuGet.Versioning;

namespace Divisima.UI.Controllers
{
	public class ProductController : Controller
	{
		IRepository<Product> repoProduct;
        public ProductController(IRepository<Product> _repoProduct)
        {
			repoProduct = _repoProduct;
        }
        public IActionResult Index()
		{
			return View();
		}

		[Route("/urun/{name}-{id}")]
		public IActionResult Detail(string name,int id)
		{
			//// 18. DERS COOKİE
			//ViewBag.CerezDegeri = Request.Cookies["C1"];


			Product product = repoProduct.GetAll(x => x.ID == id).Include(x => x.Category).Include(x => x.ProductPictures).FirstOrDefault();
			if (product != null)
			{
				//ViewBag.Title = product.Name;// layout Title ayarlayınca yap
				//return View(product);

				ProductVM productVM = new ProductVM()
				{
					Product = product,
					RelatedProducts = repoProduct.GetAll(x => x.ID == product.CategoryID && x.ID!=product.ID).Include(x => x.ProductPictures)
				};
				return View(productVM);

			}
			else
			{
				return Redirect("/");
			}
		}


		[Route("/urun/ara"), HttpPost]
		public IActionResult getSearchProduct(string search)
		{
			return Json(repoProduct.GetAll(x => x.Name.ToLower().Contains(search.ToLower())).Include
			(x => x.ProductPictures).Select(x => new SearchProduct
			{
				ProductName = x.Name,
				ProductPicture = x.ProductPictures.FirstOrDefault()
			.Picture,
				ProductLink = "/urun/" + GeneralTools.GetUrl(x.Name) + "-" + x.ID
			}));
			
		}
	}
}

Divisima/Divisima/Divisima.UI/ViewComponents/HeaderViewComponent.cs
using Divisima.BL.Repositories;
using Divisima.DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Divisima.UI.ViewComponents
{
	public class HeaderViewComponent:ViewComponent
	{
		IRepository<Category> repoCategory;
        public HeaderViewComponent(IRepository<Category> _repoCategory)
        {
            repoCategory = _repoCategory;
        }
        public IViewComponentResult Invoke()
		{
			// return View(repoCategory.GetAll().OrderBy(x => x.DisplayIndex));
			return View(repoCategory.GetAll().Include(x => x.SubCategories).OrderBy(x => x.DisplayIndex));
		}
	}
}

Divisima/Divisima/Divisima.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>
        @if (ViewBag.Title == null)
        {
            <text>Ürün Satış Sitemize Hoş geldiniz...</text>
        }
        else
        {
            @ViewBag.Title
        }
    </title>
    <meta charset="UTF-8">
    <meta name="description" content=" Divisima | eCommerce Template">
    <meta name="keywords" content="divisima, eCommerce, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Favicon -->
    <link href="/img/favicon.ico" rel="shortcut icon" />

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,300i,400,400i,700,700i" rel="stylesheet">


    <!-- Stylesheets -->
    <link rel="stylesheet" href="/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/css/font-awesome.min.css" />
        <link rel="stylesheet" href="/css/flaticon.css" />
        <link rel="stylesheet" href="/css/slicknav.min.css" />
        <link rel="stylesheet" href="/css/jquery-ui.min.css" />
        <link rel="stylesheet" href="/css/owl.carousel.min.css" />
        <link rel="stylesheet" href="/css/animate.css" />
        <link rel="stylesheet" href="/css/style.css" />


    @* BUNDLE CONFIG OLUŞTURDUKTAN SONRA *@
    @*<link href="/css/site.min.css" rel="stylesheet" />*@


    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    @await Component.InvokeAsync("Header")
    @RenderBody()
    <!-- Footer section -->
    <section class="footer-section">
        <div class="container">
            <div class="footer-logo text-center">
                <a href="index.html"><img src="/img/logo-light.png" alt=""></a>
            </div>
            <div class="row">
                <div class="col-lg-3 col-sm-6">
                    <div class="footer-widget about-widget">
                        <h2>About</h2>
                        <p>Donec vitae purus nunc. Morbi faucibus erat sit amet congue mattis. Nullam frin-gilla faucibus urna, id dapibus erat iaculis ut. Integer ac sem.</p>
                        <img src="/img/cards.png" alt="">
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="footer-widget about-widget">
                        <h2>Questions</h2>
                        <ul>
                            <li><a href="">About Us</a></li>
                            <li><a href="">Track Orders</a></li>
                            <li><a href="">Returns</a></li>
                            <li><a href="">Jobs</a></li>
                            <li><a href="">Shipping</a></li>
                            <li><a href="">Blog</a></li>
                        </ul>
                        <ul>
                            <li><a href="">Partners</a></li>
                            <li><a href="">Bloggers</a></li>
                            <li><a href="">Support</a></li>
                            <li><a href="">Terms of Use</a></li>
                            <li><a href="">Press</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="footer-widget about-widget">
                        <h2>Questions</h2>
                        <div class="fw-latest-post-widget">
                            <div class="lp-item">
                                <div class="lp-thumb set-bg" data-setbg="img/blog-thumbs/1.jpg"></div>
                                <div class="lp-content">
                                    <h6>what shoes to wear</h6>
                                    <span>Oct 21, 2018</span>
                                    <a href="#" class="readmore">Read More</a>
                                </div>
                            </div>
                            <div class="lp-item">
                                <div class="lp-thumb set-bg" data-setbg="img/blog-thumbs/2.jpg"></div>
                                <div class="lp-content">
                                    <h6>trends this year</h6>
                                    <span>Oct 21, 2018</span>
                                    <a href="#" class="readmore">Read More</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <div class="footer-widget contact-widget">
                        <h2>Questions</h2>
                        <div class="con-info">
                            <span>C.</span>
                            <p>Your Company Ltd </p>
                        </div>
                        <div class="con-info">
                            <span>B.</span>
                            <p>1481 Creekside Lane  Avila Beach, CA 93424, P.O. BOX 68 </p>
                        </div>
                        <div class="con-info">
                            <span>T.</span>
                            <p>+53 345 7953 32453</p>
                        </div>
                        <div class="con-info">
                            <span>E.</span>
                            <p>office@youremail.com</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="social-links-warp">
            <div class="container">
                <div class="social-links">
                    <a href="" class="instagram"><i class="fa fa-instagram"></i><span>instagram</span></a>
                    <a href="" class="google-plus"><i class="fa fa-google-plus"></i><span>g+plus</span></a>
                    <a href="" class="pinterest"><i class="fa fa-pinterest"></i><span>pinterest</span></a>
                    <a href="" class="facebook"><i class="fa fa-facebook"></i><span>facebook</span></a>
                    <a href="" class="twitter"><i class="fa fa-twitter"></i><span>twitter</span></a>
                    <a href="" class="youtube"><i class="fa fa-youtube"></i><span>youtube</span></a>
                    <a href="" class="tumblr"><i class="fa fa-tumblr-square"></i><span>tumblr</span></a>
                </div>

                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                <p class="text-white text-center mt-5">
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                </p>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

            </div>
        </div>
    </section>
    <!-- Footer section end -->

    @*<script src="/js/site.min.js"></script>*@

    <script src="/js/jquery-3.2.1.min.js"></script>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/jquery.slicknav.min.js"></script>
    <script src="/js/owl.carousel.min.js"></script>
    <script src="/js/jquery.nicescroll.min.js"></script>
    <script src="/js/jquery.zoom.min.js"></script>
    <script src="/js/jquery-ui.min.js"></script>
    <script src="/js/main.js"></script>



</body>
</html>

Divisima/Divisima/Divisima.UI/Views/Shared/_Product.cshtml
@model Product
<div class="product-item">
    <div class="pi-pic">
        @if (Model.ProductPictures.Any())
        {
            <img src="@Model.ProductPictures.FirstOrDefault().Picture" alt="@Model.Name">
        }
        else
        {
            <img src="/img/hazirlaniyor.jpg" alt="@Model.Name">
        }
        <div class="pi-links">
            <a asp-controller="Product"  asp-action="Detail" asp-route-name="@GeneralTools.GetUrl(Model.Name)" asp-route-id="@Model.ID" class="add-card"><i class="flaticon-bag"></i><span>SEPETE EKLE</span></a>
            <a  class="wishlist-btn"><i class="flaticon-heart"></i></a>
        </div>
    </div>
    <div class="pi-text">
        <h6>@Model.Price</h6>
        <p>@Model.Name</p>
    </div>
</div>