Divisima/Divisima/Divisima.UI/Areas/admin/Controllers/ProductController.cs
using System.Reflection.Metadata;
using Divisima.BL.Repositories;
using Divisima.DAL.Entities;
using Divisima.UI.Areas.admin.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Divisima.UI.Areas.admin.Controllers
{
	[Area("admin"), Authorize]
	public class ProductController : Controller
	{
		IRepository<Product> repoProduct;

		IRepository<Brand> repoBrand;
		IRepository<Category> repoCategory;

		public ProductController(IRepository<Product> _repoProduct, IRepository<Brand> _repoBrand, IRepository<Category> _repoCategory)
        {
			repoProduct = _repoProduct;
			repoBrand = _repoBrand;
			repoCategory = _repoCategory;
        }
        public IActionResult Index()
		{
			return View(repoProduct.GetAll().OrderByDescending(x => x.ID));
		}

		public IActionResult New()
		{
			ProductVM productVM = new ProductVM
			{
				Product = new Product(),
				Brands = repoBrand.GetAll().OrderBy(x => x.Name),
				Categories = repoCategory.GetAll(x => x.ParentID!=null).OrderBy(x => x.Name)
			};
			return View(productVM);
		}

		[HttpPost, ValidateAntiForgeryToken]
		public  IActionResult Insert(ProductVM model)
		{
			if (ModelState.IsValid)
			{
				repoProduct.Add(model.Product);

				return RedirectToAction("Index");
			}
			else return RedirectToAction("New");
		}


		public ActionResult Edit(int productid)
		{
			Product product = repoProduct.GetBy(x => x.ID == productid);
			ProductVM productVM = new ProductVM
			{
				Product = product,
				Brands = repoBrand.GetAll().OrderBy(x => x.Name),
				Categories = repoCategory.GetAll(x => x.ParentID != null).OrderBy(x => x.Name)
			};
			if (product != null) return View(productVM);
			else return RedirectToAction("Index");
		}

		[HttpPost, ValidateAntiForgeryToken]
		public IActionResult Edit(ProductVM model)
		{
			if (ModelState.IsValid) 
			{
				repoProduct.Update(model.Product);

				return RedirectToAction("Index");
			}
			else return RedirectToAction("New");
		}


		public IActionResult Delete(int id)
		{
			Product Product = repoProduct.GetBy(x => x.ID == id);
			if (Product != null) repoProduct.Delete(Product);
			return RedirectToAction("Index");
		}
	}
}

Divisima/Divisima/Divisima.UI/Areas/admin/Controllers/ProductPictureController.cs
using System.Reflection.Metadata;
using Divisima.BL.Repositories;
using Divisima.DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Divisima.UI.Areas.admin.Controllers
{
	[Area("admin"), Authorize]
	public class ProductPictureController : Controller
	{
		IRepository<ProductPicture> repoProductPicture;
        public ProductPictureController(IRepository<ProductPicture> _repoProductPicture)
        {
			repoProductPicture = _repoProductPicture;
        }
        public IActionResult Index(int productid)
		{
			ViewBag.ProductId = productid;

			return View(repoProductPicture.GetAll(x => x.ProductID == productid).OrderByDescending(x => x.ID));
		}

		public IActionResult New(int productid)
		{
			ViewBag.ProductId = productid;
			return View();
		}

		[HttpPost, ValidateAntiForgeryToken]
		public async Task<IActionResult> Insert(ProductPicture model)
		{
			if (ModelState.IsValid)
			{
				if (Request.Form.Files.Any())
				{

					if (!Directory.Exists(Path.Combine(Directory.GetCurrentDirectory(),"wwwroot","img","productPicture")))
					{
						Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "productPicture"));
					}
					string dosyaAdi = Request.Form.Files["Picture"].FileName;
					using (FileStream stream = new FileStream(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "productPicture",dosyaAdi), FileMode.Create))
					{
						await Request.Form.Files["Picture"].CopyToAsync(stream);
					}
					model.Picture = "/img/productPicture/" + dosyaAdi;
				}

				repoProductPicture.Add(model);

				return RedirectToAction("Index", new { productid = model.ProductID });
			}
			else return RedirectToAction("New");
		}


		public ActionResult Edit(int id)
		{
			ProductPicture ProductPicture = repoProductPicture.GetBy(x => x.ID == id);
			if (ProductPicture != null) return View(ProductPicture);
			else return RedirectToAction("Index");
		}

		[HttpPost, ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(ProductPicture model)
		{
			if (ModelState.IsValid)
			{
				if (Request.Form.Files.Any())
				{

					if (!Directory.Exists(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "productPicture"))) 
					{
						Directory.CreateDirectory(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "productPicture"));
					}
					string dosyaAdi = Request.Form.Files["Picture"].FileName;
					using (FileStream stream = new FileStream(Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "productPicture", dosyaAdi), FileMode.Create))
					{
						await Request.Form.Files["Picture"].CopyToAsync(stream);
					}
					model.Picture = "/img/productPicture/" + dosyaAdi;
				}
				repoProductPicture.Update(model);

				return RedirectToAction("Index", new { productid = model.ProductID });
			}
			else return RedirectToAction("New");
		}


		public IActionResult Delete(int id)
		{
			ProductPicture productPicture = repoProductPicture.GetBy(x => x.ID == id);
			if (productPicture != null)
			{
				if (!string.IsNullOrEmpty(productPicture.Picture))
				{
					string _pathFile = Directory.GetCurrentDirectory() + string.Format(@"\wwwroot") + productPicture.Picture.Replace("/", "\\");
					FileInfo fileInfo = new FileInfo(_pathFile);
					if (fileInfo.Exists) fileInfo.Delete();
				}
				repoProductPicture.Delete(productPicture);
			}

			
			return RedirectToAction("Index" , new { productid = productPicture.ProductID });
		}
	}
}

Divisima/Divisima/Divisima.UI/Controllers/ProductController.cs
using Divisima.BL.Repositories;
using Divisima.DAL.Entities;
using Divisima.UI.Models;
using Divisima.UI.Tools;
using Divisima.UI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ApplicationParts;
using Microsoft.EntityFrameworkCore;
using NuGet.Versioning;

namespace Divisima.UI.Controllers
{
	public class ProductController : Controller
	{
		IRepository<Product> repoProduct;
        public ProductController(IRepository<Product> _repoProduct)
        {
			repoProduct = _repoProduct;
        }
        public IActionResult Index()
		{
			return View();
		}

		[Route("/urun/{name}-{id}")]
		public IActionResult Detail(string name,int id)
		{
			//// 18. DERS COOKİE
			//ViewBag.CerezDegeri = Request.Cookies["C1"];


			Product product = repoProduct.GetAll(x => x.ID == id).Include(x => x.Category).Include(x => x.ProductPictures).FirstOrDefault();
			if (product != null)
			{
				//ViewBag.Title = product.Name;// layout Title ayarlayınca yap
				//return View(product);

				ProductVM productVM = new ProductVM()
				{
					Product = product,
					RelatedProducts = repoProduct.GetAll(x => x.ID == product.CategoryID && x.ID!=product.ID).Include(x => x.ProductPictures)
				};
				return View(productVM);

			}
			else
			{
				return Redirect("/");
			}
		}


		[Route("/urun/ara"), HttpPost]
		public IActionResult getSearchProduct(string search)
		{
			return Json(repoProduct.GetAll(x => x.Name.ToLower().Contains(search.ToLower())).Include
			(x => x.ProductPictures).Select(x => new SearchProduct
			{
				ProductName = x.Name,
				ProductPicture = x.ProductPictures.FirstOrDefault()
			.Picture,
				ProductLink = "/urun/" + GeneralTools.GetUrl(x.Name) + "-" + x.ID
			}));
			
		}
	}
}

Divisima/Divisima/Divisima.UI/Areas/admin/Views/Product/Edit.cshtml
@model ProductVM
<div class="right_col" role="main">
    <div class="">

        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Ürün Güncelle</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <form enctype="multipart/form-data" asp-controller="Product" asp-action="Edit" method="post" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">
                            <input type="hidden" asp-for="@Model.Product.ID" />
                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.Name"></label>
                                <div class="col-md-6 col-sm-6 ">
                                    <input class="form-control" asp-for="@Model.Product.Name">
                                    <span asp-validation-for="@Model.Product.Name"></span>
                                </div>
                            </div>

                            <!-- VIEW MODEL YAPTIKTAN SONRA -->
                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.BrandID"></label>
                                <div class="col-md-6 col-sm-6 ">
                                    <select class="form-control" asp-for="@Model.Product.BrandID" asp-items="@Model.Brands.Select(x => new SelectListItem { Text=x.Name, Value=x.ID.ToString()})">
                                        <option value="">Marka Seçiniz</option>
                                    </select>
                                    <span asp-validation-for="@Model.Product.BrandID"></span>
                                </div>
                            </div>

                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.CategoryID"></label>
                                <div class="col-md-6 col-sm-6 ">
                                    <select class="form-control" asp-for="@Model.Product.CategoryID" asp-items="@Model.Categories.Select(x => new SelectListItem { Text=x.Name, Value=x.ID.ToString()})">
                                        <option value="">Kategori Seçiniz</option>
                                    </select>
                                    <span asp-validation-for="@Model.Product.CategoryID"></span>
                                </div>
                            </div>
                            <!----------------------------------------------------------->

                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.Price"></label>
                                <div class="col-md-6 col-sm-6 ">
                                    <input class="form-control" asp-for="@Model.Product.Price">
                                    <span asp-validation-for="@Model.Product.Price"></span>
                                </div>
                            </div>

                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.Stock"></label>
                                <div class="col-md-6 col-sm-6 ">
                                    <input class="form-control" asp-for="@Model.Product.Stock">
                                    <span asp-validation-for="@Model.Product.Stock"></span>
                                </div>
                            </div>


                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.Description"></label>
                                <div class="col-md-6 col-sm-6 ">
                                    <input class="form-control" asp-for="@Model.Product.Description">
                                    <span asp-validation-for="@Model.Product.Description"></span>
                                </div>
                            </div>


                            <!--CKEDITOR GELDİKTEN SONRA YAZILACAK-->

                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.Detail"></label>
                                <div class="col-md-9 col-sm-9 ">
                                    <!--ID li-->@*<textarea id="editor1" class="form-control" asp-for="@Model.Product.Detail"></textarea>*@
                                    <!--ID siz--><textarea class="form-control editor" asp-for="@Model.Product.Detail"></textarea>


                                    <span asp-validation-for="@Model.Product.Detail"></span>
                                </div>
                            </div>

                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.CargoDetail"></label>
                                <div class="col-md-9 col-sm-9 ">
                                    <!--ID li-->@*<textarea id="editor1" class="form-control" asp-for="@Model.Product.Detail"></textarea>*@
                                    <!--ID siz--><textarea class="form-control editor" asp-for="@Model.Product.CargoDetail"></textarea>

                                    <span asp-validation-for="@Model.Product.CargoDetail"></span>
                                </div>
                            </div>


                            <!--------------------------------------->


                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.DisplayIndex"></label>
                                <div class="col-md-6 col-sm-6 ">
                                    <input class="form-control" asp-for="@Model.Product.DisplayIndex">
                                    <span asp-validation-for="@Model.Product.DisplayIndex"></span>
                                </div>
                            </div>

                            <div class="ln_solid"></div>
                            <div class="item form-group">
                                <div class="col-md-6 col-sm-6 offset-md-3">
                                    <button class="btn btn-primary" asp-controller="Product" asp-action="Index">İptal</button>
                                    <button class="btn btn-primary" type="reset">Temizle</button>
                                    <button type="submit" class="btn btn-success">Güncelle</button>
                                </div>
                            </div>
                            @Html.AntiForgeryToken()
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- /page content -->

@section customScripts{
    <script src="/admin/ckeditor/ckeditor.js"></script>
    <script>
        $(".editor").each(function () {
            CKEDITOR.replace($(this).attr("id"));
        });

        // CKEDITOR.replace($(".editor").attr("id"));   İkinci CK Editor eklenmeden önce

        //CKEDITOR.replace('editor1');  Id varken
    </script>
}

Divisima/Divisima/Divisima.UI/Areas/admin/Views/Product/Index.cshtml
@model IOrderedQueryable<Product>
<div class="right_col" role="main">
    <div class="">


        <div class="clearfix"></div>

        <div class="row" style="display: block;">


            <div class="col-md-12 col-sm-12  ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Ürün Yönetimi</h2>
                        <a asp-controller="Product" asp-action="New" class="btn btn-success float-right" style="color:#fff">Yeni Ürün</a>
                        <div class="clearfix"></div>
                    </div>

                    <div class="x_content">
                        <div class="table-responsive">
                            <table class="table table-striped jambo_table bulk_action">
                                <thead>
                                    <tr class="headings">
                                        <th class="column-title">Ürün Adı </th>
                                        <th class="column-title">Ürün Fiyatı </th>
                                        <th class="column-title">Stok Miktarı </th>
                                        <th class="column-title">Sıra </th>

                                        <!--CKEDITOR BİTİNCE GEL YAP-->
                                        <th class="column-title"></th>
                                        <th></th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach (Product s in Model)
                                    {
                                        <tr class="even pointer">

                                            <td class=" "><a asp-controller="Product" asp-action="Edit" asp-route-productid="@s.ID">@s.Name</a></td>
                                            <td class=" ">@s.Price </td>
                                            <td class=" ">@s.Stock</td>
                                            <td class=" ">@s.DisplayIndex</td>

                                            <!--CKEDITOR BİTİNCE GEL YAP-->
                                            <td class=" "><a asp-controller="ProductPicture" asp-action="Index" asp-route-productid="@s.ID">Ürüne Ait Resimler</a></td>

                                            <td><a asp-controller="Product" asp-action="Delete" asp-route-id="@s.ID" class="btn btn-danger" style="color:#fff">Sil</a></td>

                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                      

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Divisima/Divisima/Divisima.UI/Areas/admin/Views/Product/New.cshtml
@model ProductVM
<div class="right_col" role="main">
    <div class="">

        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 ">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>Yeni Ürün Ekle</h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <br />
                        <form enctype="multipart/form-data" asp-controller="Product" asp-action="Insert" method="post" id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">

                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.Name"></label>
                                <div class="col-md-9 col-sm-9 ">
                                    <input class="form-control" asp-for="@Model.Product.Name">
                                    <span asp-validation-for="@Model.Product.Name"></span>
                                </div>
                            </div>

                            <!-- VIEW MODEL YAPTIKTAN SONRA -->
                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.BrandID"></label>
                                <div class="col-md-9 col-sm-9 ">
                                    <select class="form-control" asp-for="@Model.Product.BrandID" asp-items="@Model.Brands.Select(x => new SelectListItem { Text=x.Name, Value=x.ID.ToString()})">
                                        <option value="">Marka Seçiniz</option>
                                    </select>
                                    <span asp-validation-for="@Model.Product.BrandID"></span>
                                </div>
                            </div>

                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.CategoryID"></label>
                                <div class="col-md-9 col-sm-9 ">
                                    <select class="form-control" asp-for="@Model.Product.CategoryID" asp-items="@Model.Categories.Select(x => new SelectListItem { Text=x.Name, Value=x.ID.ToString()})">
                                        <option value="">Kategori Seçiniz</option>
                                    </select>
                                    <span asp-validation-for="@Model.Product.CategoryID"></span>
                                </div>
                            </div>
                            <!----------------------------------------------------------->




                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.Price"></label>
                                <div class="col-md-9 col-sm-9 ">
                                    <input class="form-control" asp-for="@Model.Product.Price">
                                    <span asp-validation-for="@Model.Product.Price"></span>
                                </div>
                            </div>

                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.Stock"></label>
                                <div class="col-md-9 col-sm-9 ">
                                    <input class="form-control" asp-for="@Model.Product.Stock">
                                    <span asp-validation-for="@Model.Product.Stock"></span>
                                </div>
                            </div>


                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.Description"></label>
                                <div class="col-md-9 col-sm-9 ">
                                    <input class="form-control" asp-for="@Model.Product.Description">
                                    <span asp-validation-for="@Model.Product.Description"></span>
                                </div>
                            </div>

                            <!--CKEDITOR GELDİKTEN SONRA YAZILACAK-->

                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.Detail"></label>
                                <div class="col-md-9 col-sm-9 ">
                                    <!--ID li-->@*<textarea id="editor1" class="form-control" asp-for="@Model.Product.Detail"></textarea>*@
                                    <!--ID siz--><textarea class="form-control editor" asp-for="@Model.Product.Detail"></textarea>


                                    <span asp-validation-for="@Model.Product.Detail"></span>
                                </div>
                            </div>

                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.CargoDetail"></label>
                                <div class="col-md-9 col-sm-9 ">
                                    <!--ID li-->@*<textarea id="editor1" class="form-control" asp-for="@Model.Product.Detail"></textarea>*@
                                    <!--ID siz--><textarea class="form-control editor" asp-for="@Model.Product.CargoDetail"></textarea>

                                    <span asp-validation-for="@Model.Product.CargoDetail"></span>
                                </div>
                            </div>


                            <!--------------------------------------->

                            <div class="item form-group">
                                <label class="col-form-label col-md-3 col-sm-3 label-align" asp-for="@Model.Product.DisplayIndex"></label>
                                <div class="col-md-9 col-sm-9 ">
                                    <input class="form-control" asp-for="@Model.Product.DisplayIndex">
                                    <span asp-validation-for="@Model.Product.DisplayIndex"></span>
                                </div>
                            </div>

                            <div class="ln_solid"></div>
                            <div class="item form-group">
                                <div class="col-md-9 col-sm-9 offset-md-3">
                                    <button class="btn btn-primary" asp-controller="Product" asp-action="Index">İptal</button>
                                    <button class="btn btn-primary" type="reset">Temizle</button>
                                    <button type="submit" class="btn btn-success">Ekle</button>
                                </div>
                            </div>
                            @Html.AntiForgeryToken()
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- /page content -->

@section customScripts{
    <script src="/admin/ckeditor/ckeditor.js"></script>
    <script>
        $(".editor").each(function () {
            CKEDITOR.replace($(this).attr("id"));
        });

        // CKEDITOR.replace($(".editor").attr("id"));   İkinci CK Editor eklenmeden önce

        //CKEDITOR.replace('editor1');  Id varken
    </script>
}